export const LOGIN = "LOGIN";
export const PRE_ACTIVATION_LOGIN = "PRE_ACTIVATION_LOGIN";
export const LOGIN_FACEBOOK = "LOGIN_FACEBOOK";
export const LOGOUT = "LOGOUT";
export const SET_LANDING_PATH = "SET_LANDING_PATH";
export const STORE_USER = "STORE_USER";

export const SET_LOCALE = "SET_LOCALE";
export const SET_DIMENSIONS = "SET_DIMENSIONS";
export const SHOW_PASSWORD = "SHOW_PASSWORD";

export const CLEAR_FIELDS = "CLEAR_FIELDS";
export const UPDATE_FIELDS = "UPDATE_FIELDS";

export const UPDATE_PROGRESS = "UPDATE_PROGRESS";
export const CLEAR_PROGRESS = "CLEAR_PROGRESS";

export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
export const INFO_NOTIFICATION = "INFO_NOTIFICATION";
export const WARNING_NOTIFICATION = "WARNING_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const SHOW_MENU = "SHOW_MENU";
export const HIDE_MENU = "HIDE_MENU";
export const SHOW_TOPBAR = "SHOW_TOPBAR";
export const HIDE_TOPBAR = "HIDE_TOPBAR";
export const HIDE_TOPBAR_BTN = "HIDE_TOPBAR_BTN";
export const SHOW_TOPBAR_BTN = "SHOW_TOPBAR_BTN";
export const UPDATE_TOPBAR_BTN = "UPDATE_TOPBAR_BTN";

export const LOAD = "LOAD";

export const SEND_PASSWORD_RESET = "SEND_PASSWORD_RESET";

export const SET_GENDER = "SET_GENDER";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const UPDATE_GLOBAL_THEME = "UPDATE_GLOBAL_THEME";

export const POSTCODE_LOOKUP_RESULT = "POSTCODE_LOOKUP_RESULT";
export const POSTCODE_CLEAR_RESULT = "POSTCODE_CLEAR_RESULT";

export const SHOW_TOPBAR_CENTER_TEXT = "SHOW_TOPBAR_CENTER_TEXT";
export const HIDE_TOPBAR_CENTER_TEXT = "HIDE_TOPBAR_CENTER_TEXT";
export const SHOW_TOPBAR_LEFT_TEXT = "SHOW_TOPBAR_LEFT_TEXT";
export const HIDE_TOPBAR_LEFT_TEXT = "HIDE_TOPBAR_CENTER_TEXT";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";

export const GET_SELECTED_PROPERTY = "GET_SELECTED_PROPERTY";

export const STORE_INITIAL_VALUES = "STORE_INITIAL_VALUES";
export const GET_RENT_PASSPORTS = "GET_RENT_PASSPORTS";
export const STORE_PASSPORT = "STORE_PASSPORT";

export const GET_PROPERTY = "GET_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const GET_PROPERTY_LIST = "GET_PROPERTY_LIST";
export const GET_PROPERTY_PASSPORTS_GROUP = "GET_PROPERTY_PASSPORTS_GROUP";
export const GET_PROPERTY_ACTIVE_LEASE = "GET_PROPERTY_ACTIVE_LEASE";

export const GET_AGENT = "GET_AGENT";
export const REMOVE_AGENT = "REMOVE_AGENT";

export const GET_AGENCY_BRANCHES = "GET_AGENCY_BRANCHES";
export const BRANCH_PROPERTIES_RECEIVED = "BRANCH_PROPERTIES_RECEIVED";
export const BRANCH_SELECTED = "BRANCH_SELECTED";
export const CLEAR_CURRENT_BRANCH = "CLEAR_CURRENT_BRANCH";
export const CLEAR_BRANCH_PROPERTIES = "CLEAR_BRANCH_PROPERTIES";

export const GET_USER = "GET_USER";
export const GET_USER_PREFERENCES = "GET_USER_PREFERENCES";

export const HIDE_BACK_BUTTON = "HIDE_BACK_BUTTON";
export const SHOW_BACK_BUTTON = "SHOW_BACK_BUTTON";

export const SET_BRANCH_RENT_PASSPORTS = "SET_BRANCH_RENT_PASSPORTS";
export const RENT_PASSPORT_IS_ALREADY_SHARED =
  "RENT_PASSPORT_IS_ALREADY_SHARED";

export const GET_RENT_PASSPORT = "GET_RENT_PASSPORT";
export const DELETE_RENT_PASSPORT = " DELETE_RENT_PASSPORT";

export const GET_PASSPORTS = "GET_PASSPORTS";
export const SHOW_PASSPORT_OPTIONS = "SHOW_PASSPORT_OPTIONS";
export const STORE_PASSPORT_CHECKLIST = "STORE_PASSPORT_CHECKLIST";
export const RESET_CHECKED_PASSPORTS = "RESET_CHECKED_PASSPORTS";
export const RENT_PASSPORTS_SHARES_RECEIVED = "RENT_PASSPORTS_SHARES_RECEIVED";
export const UNSHARE_PASSPORT = "UNSHARE_PASSPORT";

export const UPDATE_SELECTED_BRANCH = "UPDATE_SELECTED_BRANCH";

export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";

export const LEASES_LOOKUP_RESULT = "LEASES_LOOKUP_RESULT";
export const STORE_BACK_PHOTO = "STORE_BACK_PHOTO";
export const STORE_PHOTO = "STORE_PHOTO";

export const STORE_TOKEN = "STORE_TOKEN";
export const CLEAR_TOKEN = "CLEAR_TOKEN";

export const SELECT_AGENCY_TYPE = "SELECT_AGENCY_TYPE";
export const OPEN_BANKING_METADATA = "OPEN_BANKING_METADATA";
export const OPEN_BANKING_CREDENTIALS_VERIFIED =
  "OPEN_BANKING_CREDENTIALS_VERIFIED";
export const OPEN_BANKING_TRANSACTIONS = "OPEN_BANKING_TRANSACTIONS";
export const OPEN_BANKING_TRANSACTIONS_CLEAR =
  "OPEN_BANKING_TRANSACTIONS_CLEAR";
