export default {
  userId: "67e4b887-466e-4abe-8d12-bc87204e5df8",
  status: "SUBMITTED",
  aboutInfo: {
    email: "jonathan@gmail.com",
    firstName: "Jonathan",
    lastName: "Beaumont",
    middleName: null,
    gender: "MALE",
    dayOfBirth: 20,
    monthOfBirth: 11,
    yearOfBirth: 1970,
    maritalStatus: "MARRIED",
    phoneNumber: "01123456789",
    nationality: "UK",
    isSmoker: true,
    hasPets: true,
    hasChildren: true,
    status: "GREEN",
    messages: [],
  },
  annualIncomeInfo: {
    salary: 100000,
    pension: 0,
    interest: 0,
    benefits: 0,
    rentals: 0,
    other: 0,
    grossAnnualIncome: 100000,
    sourcesOfIncome: ["Employment"],
    status: "YELLOW",
    messages: [],
  },
  financialInfo: {
    bankrupt: false,
    creditScore: 930,
    depositFree: true,
    maximumEligible: 1800.266,
    activeCCJs: 0,
    activeCCJYear: 0,
    activeCCJMonth: 0,
    activeCCJValue: 0,
    previousCCJs: 0,
    previousCCJsYear: 0,
    previousCCJsMonth: 0,
    activeInsolvencies: 0,
    activeInsolvenciesYear: 0,
    activeInsolvenciesMonth: 0,
    previousInsolvencies: false,
    previousInsolvenciesYear: 0,
    previousInsolvenciesMonth: 0,
    status: "GREEN",
    messages: [],
  },
  legalInfo: {
    pep: false,
    mortality: "passed",
    legalWarnings: false,
    sanctions: false,
    status: "GREEN",
    messages: [],
  },
  workInfo: [
    {
      workStatus: "EMPLOYED",
      companyName: "companyName",
      jobTitle: "jobTitle",
      income: 100000,
      employmentTime: "FULL_TIME",
      employmentType: "CONTRACT",
      workedSinceMonth: 12,
      workedSinceYear: 2017,
      studentType: "POST_GRADUATE_STUDENT",
      reference: {
        contactFirstName: "Silvester",
        contactLastName: "Stallone",
        contactEmailAddress: "rambo666@gmail.com",
        referredAt: "12-12-2016",
      },
      status: "GREEN",
      messages: [],
    },
  ],
  residenceInfo: [
    {
      line1: "Addresss line 1",
      town: "Town",
      state: "State",
      postCode: "UL11223",
      countryCode: "UK",
      residenceType: "RENTING_FROM_AGENT",
      livedSinceMonth: 1,
      livedSinceYear: 2016,
      livedToMonth: null,
      livedToYear: null,
      reference: {
        contactFirstName: "Jonathan",
        contactLastName: "Beaumont",
        contactEmailAddress: "jonathan@gmail.com",
        referredAt: "01-01-2018",
      },
      status: "GREEN",
      messages: [],
    },
  ],
};
