import {extend} from "underscore";

export const getMockPropertiesAsArray = () => {
  return Object.values(getMockProperties());
};

export const getMockProperties = () => ({
  hasPrimaryImageNotAtZero: {
    id: "abc-123",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-456",
        url: "http://www.findyourcanopy.com/img123.jpeg",
        isPrimary: false,
      },
      {
        id: "def-457",
        url: "http://www.findyourcanopy.com/img124.jpeg",
        isPrimary: true,
      },
      {
        id: "def-458",
        url: "http://www.findyourcanopy.com/img125.jpeg",
        isPrimary: false,
      },
    ],
    landlord: {},
    address: {
      line1: "29 Acacia Road",
      town: "Beanotown",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasNoImages: {
    id: "abc-124",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    landlord: {},
    address: {
      line1: "30 Acacia Road",
      line2: "Clifton",
      town: "Beanotown",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasPrimaryImageAtZero: {
    id: "abc-125",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img127.jpeg",
        isPrimary: true,
      },
      {
        id: "def-460",
        url: "http://www.findyourcanopy.com/img128.jpeg",
        isPrimary: false,
      },
      {
        id: "def-461",
        url: "http://www.findyourcanopy.com/img129.jpeg",
        isPrimary: false,
      },
    ],
    landlord: {},
    address: {
      line1: "31 Acacia Road",
      town: "Beanotown",
      postCode: "BE1 1BE",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasNoPrimaryImage: {
    id: "abc-135",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img144.jpeg",
      },
      {
        id: "def-460",
        url: "http://www.findyourcanopy.com/img145.jpeg",
        isPrimary: false,
      },
      {
        id: "def-461",
        url: "http://www.findyourcanopy.com/img146.jpeg",
      },
    ],
    landlord: {},
    address: {
      line1: "31 Acacia Road",
      town: "Beanotown",
      postCode: "BE1 1BE",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasMixOfImagesOneIsPrimaryRestMayNotHaveField: {
    id: "abc-126",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-465",
        url: "http://www.findyourcanopy.com/img130.jpeg",
      },
      {
        id: "def-466",
        url: "http://www.findyourcanopy.com/img131.jpeg",
        isPrimary: false,
      },
      {
        id: "def-467",
        url: "http://www.findyourcanopy.com/img132.jpeg",
        isPrimary: false,
      },
      {
        id: "def-468",
        url: "http://www.findyourcanopy.com/img133.jpeg",
        isPrimary: true,
      },
      {
        id: "def-469",
        url: "http://www.findyourcanopy.com/img134.jpeg",
      },
      {
        id: "def-470",
        url: "http://www.findyourcanopy.com/img135.jpeg",
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasTownNoCity: {
    id: "abc-127",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img136.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasCityNoTown: {
    id: "abc-128",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img137.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      city: "Aberdeen",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasCityAndTown: {
    id: "abc-129",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img138.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      city: "Aberdeen",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasWeeklyRent: {
    id: "abc-130",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img139.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      city: "Aberdeen",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasFortnightlyRent: {
    id: "abc-131",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "FORTNIGHTLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img140.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      city: "Aberdeen",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasFourWeeklyRent: {
    id: "abc-132",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "FOUR_WEEKLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img141.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      city: "Aberdeen",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasMonthlyRent: {
    id: "abc-133",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "MONTHLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img142.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      city: "Aberdeen",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
  hasYearlyRent: {
    id: "abc-134",
    presentation: {
      bathroomsCount: 1,
      bedroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasOutsideSpace: true,
      hasParking: true,
      petsAllowed: false,
      propertyType: "HOUSE",
      smokingAllowed: false,
    },
    rentFrequency: "YEARLY",
    rentAmount: 1234.99,
    depositAmount: 1000,
    depositFreeAvailable: true,
    propertyImages: [
      {
        id: "def-459",
        url: "http://www.findyourcanopy.com/img143.jpeg",
        isPrimary: true,
      },
    ],
    landlord: {},
    address: {
      line1: "32 Acacia Road",
      town: "Beanotown",
      city: "Aberdeen",
      state: "Aberdeenshire",
      postCode: "BE1 1BE",
      countryCode: "UK",
    },
    createdBy: "Homogenous cohorts",
    agencyId: "22",
    branchId: "44",
  },
});

export const getMockTranslations = translations => {
  const parsedTranslations = extend(
    {
      currency_symbol: "£",
    },
    translations,
  );
  parsedTranslations.rental_period_abbreviations = extend(
    {
      weekly: "w",
      fortnightly: "f",
      four_weekly: "fw",
      monthly: "m",
      yearly: "y",
    },
    (translations && translations.rental_period_abbreviations) || {},
  );

  return parsedTranslations;
};
