// eslint-disable-next-line no-unused-vars
export const defaultProperty = {
  property: {
    id: "12",
    rentPassportsGroup: {
      passports: [
        {
          id: "0",
          email: "jonathan@gmail.com",
          userId: "jonathan_userId",
          passport: {
            aboutInfo: {
              email: "jonathan@gmail.com",
              firstName: "Jonathan",
              lastName: "Beaumont",
              middleName: "Charles",
              gender: "MALE",
              dayOfBirth: 1,
              monthOfBirth: 1,
              yearOfBirth: 1970,
              maritalStatus: "MARRIED",
              phoneNumber: "01123456789",
              nationality: "UK",
              isSmoker: true,
              hasPets: true,
              hasChildren: true,
            },
            residenceInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "Jonathan",
                contactLastName: "Beaumont",
                contactEmailAddress: "jonathan@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            workInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "Jonathan",
                contactLastName: "Beaumont",
                contactEmailAddress: "jonathan@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            annualIncomeInfo: {
              salary: 11,
              pension: 11,
              interest: 11,
              benefits: 11,
              rentals: 11,
              other: 11,
            },
          },
          expiresAt: "01-01-2018",
          status: "SHARED",
        },
        {
          id: "1",
          email: "james-wang@gmail.com",
          userId: "james_userId",
          passport: {
            aboutInfo: {
              email: "james-wang@gmail.com",
              firstName: "James",
              lastName: "Wang",
              middleName: "Charles",
              gender: "MALE",
              dayOfBirth: 1,
              monthOfBirth: 1,
              yearOfBirth: 1970,
              maritalStatus: "MARRIED",
              phoneNumber: "01123456789",
              nationality: "UK",
              isSmoker: true,
              hasPets: true,
              hasChildren: true,
            },
            residenceInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "James",
                contactLastName: "Wang",
                contactEmailAddress: "james-wang@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            workInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "James",
                contactLastName: "Wang",
                contactEmailAddress: "james-wang@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            annualIncomeInfo: {
              salary: 11,
              pension: 11,
              interest: 11,
              benefits: 11,
              rentals: 11,
              other: 11,
            },
          },
          expiresAt: "01-01-2018",
          status: "EXPIRED",
        },
        {
          id: "2",
          email: "joshua_yates99@gmail.com",
          userId: "joshua_yates99",
          passport: {
            aboutInfo: {
              email: "joshua_yates99@gmail.com",
              firstName: "Joshua",
              lastName: "Yates",
              middleName: "Yates",
              gender: "MALE",
              dayOfBirth: 1,
              monthOfBirth: 1,
              yearOfBirth: 1970,
              maritalStatus: "MARRIED",
              phoneNumber: "01123456789",
              nationality: "UK",
              isSmoker: true,
              hasPets: true,
              hasChildren: true,
            },
            residenceInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "James",
                contactLastName: "Wang",
                contactEmailAddress: "james-wang@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            workInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "James",
                contactLastName: "Wang",
                contactEmailAddress: "james-wang@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            annualIncomeInfo: {
              salary: 11,
              pension: 11,
              interest: 11,
              benefits: 11,
              rentals: 11,
              other: 11,
            },
          },
          expiresAt: "01-01-2018",
          status: "PENDING",
        },
        {
          id: "3",
          email: "jennifer-jones@gmail.com",
          userId: "jennifer-jones_id",
          passport: {
            aboutInfo: {
              email: "jennifer-jones@gmail.com",
              firstName: "Jennifer",
              lastName: "Jones",
              middleName: "Charles",
              gender: "FEMALE",
              dayOfBirth: 1,
              monthOfBirth: 1,
              yearOfBirth: 1970,
              maritalStatus: "MARRIED",
              phoneNumber: "01123456789",
              nationality: "UK",
              isSmoker: true,
              hasPets: true,
              hasChildren: true,
            },
            residenceInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "James",
                contactLastName: "Wang",
                contactEmailAddress: "james-wang@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            workInfo: {
              residenceType: "RENTING_FROM_AGENT",
              livedSinceMonth: 1,
              livedSinceYear: 1,
              livedToMonth: null,
              livedToYear: null,
              reference: {
                contactFirstName: "James",
                contactLastName: "Wang",
                contactEmailAddress: "james-wang@gmail.com",
                referredAt: "01-01-2018",
              },
            },
            annualIncomeInfo: {
              salary: 11,
              pension: 11,
              interest: 11,
              benefits: 11,
              rentals: 11,
              other: 11,
            },
          },
          expiresAt: "01-01-2019",
          status: "CANCELLED",
        },
      ],
    },

    presentation: {
      propertyType: "APARTMENT",
      bedroomsCount: 2,
      bathroomsCount: 2,
      furnishedType: "PART_FURNISHED",
      hasParking: true,
      hasOutsideSpace: true,
      petsAllowed: true,
      smokingAllowed: false,
      dateAvailable: "11-12-2019",
      summary: "2 bed apartment to rent",
      description:
        "Well presented ground floor apartment available on Stamford Street. The property is offered unfurnished and comprises entrance hallway, downstairs WC, lounge/diner with doors to balcony/terrace, storage cupboards, kitchen with white goods including electric cooke. Well presented ground floor apartment available on Stamford Street. The property is offered unfurnished and comprises entrance hallway, downstairs WC, lounge/diner with doors to balcony/terrace, storage cupboards, kitchen with white goods including electric cooker.",
    },
    rentFrequency: "MONTHLY",
    rentAmount: 1200,
    depositAmount: 1800,
    depositFreeAvailable: true,
    landlord: {
      firstName: "firstName",
      lastName: "lastName",
      email: "landlord1@gmail.com",
      phone: "01234567890",
      address: {
        line1: "Address line 1",
        line2: "Address line 2",
        town: "City / Town",
        state: "State",
        postCode: "FYC123",
        countryCode: "UK",
      },
    },
    createdBy: "67e4b887-466e-4abe-8d12-bc87204e5df8",
    agencyId: "67e4b887-466e-4abe-8d12-bc87204e5df8",
    branchId: "01a5b187-313s-7gtc-4a31-av51034r1ea1",
    createdAt: "01-01-2017",
    updatedAt: "01-01-2017",
    propertyImages: [
      {
        id: "0",
        url:
          "http://cdn.home-designing.com/wp-content/uploads/2016/04/luxury-art-deco-apartment-interior.jpg",
        isPrimary: true,
        createdAt: "01-01-2017",
        updatedAt: "01-01-2017",
        version: 1,
      },
      {
        id: "1",
        url:
          "http://cdn.home-designing.com/wp-content/uploads/2016/04/luxury-art-deco-apartment-interior.jpg",
        isPrimary: false,
        createdAt: "01-01-2017",
        updatedAt: "01-01-2017",
        version: 1,
      },
      {
        id: "2",
        url:
          "http://cdn.home-designing.com/wp-content/uploads/2016/04/luxury-art-deco-apartment-interior.jpg",
        isPrimary: false,
        createdAt: "01-01-2017",
        updatedAt: "01-01-2017",
        version: 1,
      },
    ],
    address: {
      line1: "Address line 1",
      line2: "Address line 2",
      town: "City / Town",
      state: "State",
      postCode: "FYC123",
      countryCode: "UK",
    },
  },
};

// eslint-disable-next-line no-unused-vars
export const defaultPassports = [
  {
    id: 1991,
    status: "SUBMITTED",
    aboutInfo: {
      email: "jonathan@gmail.com",
      firstName: "Jonathan",
      lastName: "Beaumont",
      middleName: null,
      gender: "MALE",
      dayOfBirth: 20,
      monthOfBirth: 11,
      yearOfBirth: 1970,
      maritalStatus: "MARRIED",
      phoneNumber: "01123456789",
      nationality: "UK",
      isSmoker: true,
      hasPets: true,
      hasChildren: true,
      status: "GREEN",
      messages: [],
    },
    annualIncomeInfo: {
      salary: 100000,
      pension: 0,
      interest: 0,
      benefits: 0,
      rentals: 0,
      other: 0,
      grossAnnualIncome: 100000,
      sourcesOfIncome: ["Employment"],
      status: "GREEN",
      messages: [],
    },
    financialInfo: {
      bankrupt: false,
      creditScore: 930,
      depositFree: true,
      maximumEligible: 1800.266,
      activeCCJs: 0,
      activeCCJYear: 0,
      activeCCJMonth: 0,
      activeCCJValue: 0,
      previousCCJs: 0,
      previousCCJsYear: 0,
      previousCCJsMonth: 0,
      activeInsolvencies: 0,
      activeInsolvenciesYear: 0,
      activeInsolvenciesMonth: 0,
      previousInsolvencies: false,
      previousInsolvenciesYear: 0,
      previousInsolvenciesMonth: 0,
      status: "GREEN",
      messages: [],
    },
    legalInfo: {
      pep: false,
      mortality: "passed",
      legalWarnings: false,
      sanctions: false,
      status: "GREEN",
      messages: [],
    },
    rightToRentInfo: {
      documentStatus: "verified",
      legalWarnings: false,
      documentSample:
        "https://www.apostille.org.uk/sites/default/files/sample-passport700w-wm.gif",
      sanctions: false,
      status: "GREEN",
      messages: [],
    },
    workInfo: [
      {
        workStatus: "EMPLOYED",
        companyName: "companyName",
        jobTitle: "jobTitle",
        income: 100000,
        employmentTime: "FULL_TIME",
        employmentType: "CONTRACT",
        workedSinceMonth: 12,
        workedSinceYear: 2017,
        studentType: "POST_GRADUATE_STUDENT",
        reference: {
          contactFirstName: "Silvester",
          contactLastName: "Stallone",
          contactEmailAddress: "rambo666@gmail.com",
          referredAt: "12-12-2016",
        },
        status: "GREEN",
        messages: [],
      },
    ],
    residenceInfo: [
      {
        line1: "Addresss line 1",
        town: "Town",
        state: "State",
        postCode: "UL11223",
        countryCode: "UK",
        residenceType: "RENTING_FROM_AGENT",
        livedSinceMonth: 1,
        livedSinceYear: 2016,
        livedToMonth: null,
        livedToYear: null,
        reference: {
          contactFirstName: "Jonathan",
          contactLastName: "Beaumont",
          contactEmailAddress: "jonathan@gmail.com",
          referredAt: "01-01-2018",
        },
        status: "GREEN",
        messages: [],
      },
    ],
  },
  {
    id: 666,
    name: "James Wang",
    status: "Partially referenced",
  },
  {
    id: 111,
    name: "Jennifer Jones",
    status: "Not fully referenced",
  },
  {
    id: 133,
    name: "joshua_yates99@hotmail.com",
    pending: true,
  },
  {
    id: 134,
    name: "bob_marley66@hotmail.com",
    pending: true,
  },
];
